name: Android release

on:
  release:
    types:
      - created

  build:
    name: Build everthing, test and report
    runs-on: ubuntu-latest
    needs: [setup]
    if: contains(github.ref, '+android')
    steps:
      - name: boo
        run: |          
          echo "Hello!"
                    